APP_NAME = "MyApp"
DEV_ENV = "dev"

# Demo agent constants
DEMO_AGENT_ENDPOINT = "DEMO_AGENT_ENDPOINT"
DEMO_AGENT_ID = "DEMO_AGENT_ID"

# Developed agent constants
DEVELOPED_AGENT_PROJECT_ENDPOINT= "DEVELOPED_AGENT_PROJECT_ENDPOINT"
MODEL_DEPLOYMENT_NAME= "MODEL_DEPLOYMENT_NAME"